In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [16]:
import numpy as np
import pandas as pd
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=["cgpa","profile_score","lpa"])

In [7]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [29]:
model=Sequential()

model.add(Dense(2,activation="linear",input_dim=2))
model.add(Dense(1,activation="linear"))

In [30]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.get_weights()

[array([[-0.42096633, -0.09227526],
        [-0.76857626,  0.9627851 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0977798],
        [ 0.4929279]], dtype=float32),
 array([0.], dtype=float32)]

In [38]:
new_weights=[np.array([[0.1 , 0.1],
                       [0.1 , 0.1]],dtype=np.float32),
                     np.array([0. , 0.],dtype=np.float32),
                     np.array([[0.1],
                        [0.1]],dtype=np.float32),
                    np.array([0.],dtype=np.float32)]

In [39]:
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [40]:
model.set_weights(new_weights)

In [41]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [42]:
optimizres=keras.optimizers.Adam(learning_rate=0.001)

In [50]:
model.compile(loss="mean_squared_error",optimizer=optimizres)

In [51]:
#extracat x and y from the data
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [45]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1:]

In [52]:
model.fit(x,y,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 33.2070  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.6180 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8871 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.9032 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.3871 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.1377 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28.9414 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.1140 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22.9629 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28.3521 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.9013 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8024 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.9952 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.4972 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.1938
Epoch 16/75
4/4 ━━━

In [53]:
model.get_weights()

[array([[0.37385935, 0.37385935],
        [0.36566186, 0.36566186]], dtype=float32),
 array([0.27246276, 0.27246276], dtype=float32),
 array([[0.37305528],
        [0.37305528]], dtype=float32),
 array([0.20475313], dtype=float32)]

In [55]:
#Now the same thing for Classification problem.

In [56]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=["cgpa","profile_score","placment"])

In [57]:
df

cgpa  profile_score  placment
0     8              8         1
1     7              9         1
2     6             10         0
3     5              5         0

In [58]:
#again extracting the data x and y from the data.
x=df.iloc[:,:-1]
y=df.iloc[:,-1:]

In [65]:
model=Sequential()
model.add(Dense(2,activation="sigmoid",input_dim=2))
model.add(Dense(1,activation="sigmoid"))

In [66]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [67]:
model.get_weights()

[array([[-0.04101777, -0.39123005],
        [ 0.33917284, -0.9199851 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.3488623],
        [ 0.8616866]], dtype=float32),
 array([0.], dtype=float32)]

In [68]:
new_weights=[np.array([[0.1 , 0.1],
                       [0.1 , 0.1]],dtype=np.float32),
                     np.array([0. , 0.],dtype=np.float32),
                     np.array([[0.1],
                        [0.1]],dtype=np.float32),
                    np.array([0.],dtype=np.float32)]

In [70]:
model.set_weights(new_weights)

In [71]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [72]:
optimizres=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="binary_crossentropy",optimizer=optimizres)

In [76]:
model.fit(x,y,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7067 
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7162 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7127 
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6830 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6742 
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7058 
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6840 
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7279 
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7017 
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6728 
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7054 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6831 
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7117 
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6590 
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7147 
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━

In [77]:
model.get_weights()

[array([[0.09991723, 0.09991723],
        [0.08508684, 0.08508684]], dtype=float32),
 array([-0.03172759, -0.03172759], dtype=float32),
 array([[0.09065152],
        [0.09065152]], dtype=float32),
 array([-0.01568391], dtype=float32)]