In [46]:
#Lasso craeat sparcity because the alpha formed in the neumerator of m so thats why it creat sparcity but in the ridge regression the alpha formed in the denominator
#alpha formed in denominator so thats why ridge regression not creat sparcity.
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.linear_model import Ridge,Lasso,LinearRegression
from sklearn.metrics import r2_score

In [4]:
x,y=load_diabetes(return_X_y=True)

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
rid=Ridge(alpha=1.0)

In [14]:
rid.fit(x_train,y_train)

Ridge()

In [15]:
rid.coef_

array([  45.36737726,  -76.66608563,  291.33883165,  198.99581745,
         -0.53030959,  -28.57704987, -144.51190505,  119.26006559,
        230.22160832,  112.14983004])

In [16]:
rid.intercept_

152.241675211113

In [19]:
y_pred=rid.predict(x_test)
r2_score(y_test,y_pred)*100

41.915292635986546

In [29]:
laso=Lasso(alpha=0.1)

In [30]:
laso.fit(x_train,y_train)

Lasso(alpha=0.1)

In [31]:
laso.coef_

array([   0.        , -152.66477923,  552.69777529,  303.36515791,
        -81.36500664,   -0.        , -229.25577639,    0.        ,
        447.91952518,   29.64261704])

In [32]:
laso.intercept_

151.57485282893947

In [34]:
result=laso.predict(x_test)
r2_score(y_test,result)*100

47.18547867276227

In [38]:
lr=LinearRegression()

In [39]:
lr.fit(x_train,y_train)

LinearRegression()

In [40]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [41]:
lr.intercept_

151.34560453985995

In [43]:
y=lr.predict(x_test)

In [45]:
r2_score(y_test,y)*100

45.26027629719197

In [47]:
#Thera is another technique which is the subset of lasso and ridge that we will cover in the next day.