In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df=pd.DataFrame({'text':["people watch campux","campux watch campux","people write comment","campux write comment"],'output':[1,1,0,0]})

# Aplly BAG OF WORDS TECHNIQUE

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
cv=CountVectorizer()
bow=cv.fit_transform(df["text"])

In [18]:
print(cv.vocabulary_)
print(bow.toarray())

{'people': 2, 'watch': 3, 'campux': 0, 'write': 4, 'comment': 1}
[[1 0 1 1 0]
 [2 0 0 1 0]
 [0 1 1 0 1]
 [1 1 0 0 1]]


In [19]:
cv.transform(["campux watch campux and watch campux also"]).toarray()

array([[3, 0, 0, 2, 0]])

# Applaying N-Gram TECHNIQUE

In [20]:
df=pd.DataFrame({'text':["people watch campux","campux watch campux","people write comment","campux write comment"],'output':[1,1,0,0]})

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
cv=CountVectorizer(ngram_range=(2,2))
bow=cv.fit_transform(df["text"])

In [37]:
print(cv.vocabulary_)
print(bow.toarray())

{'people watch': 2, 'watch campux': 4, 'campux watch': 0, 'people write': 3, 'write comment': 5, 'campux write': 1}
[[0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 1 0 1]
 [0 1 0 0 0 1]]


# TF-IDF ( term frequnecy - inverse documnet frequenct )

In [38]:
df=pd.DataFrame({'text':["people watch campux","campux watch campux","people write comment","campux write comment"],'output':[1,1,0,0]})

In [40]:
df

text  output
0   people watch campux       1
1   campux watch campux       1
2  people write comment       0
3  campux write comment       0

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [44]:
tf_idf = TfidfVectorizer()
tf_idf.fit_transform(df["text"]).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [49]:
print(tf_idf.idf_) 
print(tf_idf.get_feature_names_out()) 

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campux' 'comment' 'people' 'watch' 'write']


# interview question why take log while implementing idf????

# idf value will be very high so its dominate to tf so thats why we take log to make smooth the situation