In [1]:
import pandas as pd
import numpy as np 
from sklearn.datasets import make_classification

In [213]:
x,y=make_classification(n_samples=1000,n_features=5,n_informative=2)

In [214]:
df=pd.DataFrame(x)
df=df.rename(columns={
    0:"col1",
    1:"col2",
    3:"col3",
    4:"col4",
    5:"col5"}
)
dt=pd.DataFrame(y)
dt=dt.rename(columns={
    0:"target"
})

In [215]:
dt.sample(2)

target
809       0
253       0

In [216]:
df=pd.concat((df,dt),axis=1)

In [228]:
import random

In [218]:
def row_sample(df,row_percent):
    return df.sample(int(row_percent * df.shape[0]),replace=True)

In [231]:
def feature_sample(df,col_percent):
    cols=random.sample(df.columns.tolist()[:-1],int(col_percent * df.shape[1]))
    return df[cols]

In [224]:
df1=row_sample(df,0.3)

In [235]:
clf1=feature_sample(df,0.5)
clf2=feature_sample(df,0.5)
clf3=feature_sample(df,0.5)

In [237]:
clf1.head(2)

col2      col4      col3
0  1.289051 -0.327374 -0.829221
1 -0.491990 -0.542995  0.532271

In [238]:
clf2.head(2)

col1      col3         2
0 -0.453723 -0.829221  0.413706
1  0.233554  0.532271 -0.156861

In [239]:
clf3.head(2)

col2         2      col3
0  1.289051  0.413706 -0.829221
1 -0.491990 -0.156861  0.532271

In [241]:
df2=row_sample(df,0.3)

In [242]:
df2.head(4)

col1      col2         2      col3      col4  target
306 -0.516256  0.955630  0.303607 -1.257603 -0.372883       1
458 -0.379992  0.508866  0.159862 -1.045216 -0.206817       1
674 -0.056000 -0.769023 -0.252424 -0.672748  2.548748       0
59   0.111319  0.054634  0.019778  0.431392  0.586694       1

In [243]:
df3=row_sample(df,0.3)

In [244]:
df3.head(3)

col1      col2         2      col3      col4  target
931  0.928001 -2.186662 -0.699063  1.972466 -1.379436       0
27   0.073466  0.916491  0.300944  0.825797  1.183169       1
7   -0.331611 -0.991313 -0.329847 -1.794295 -0.257971       0

In [245]:
from sklearn.tree import DecisionTreeClassifier

In [246]:
Model1=DecisionTreeClassifier()
Model2=DecisionTreeClassifier()
Model3=DecisionTreeClassifier()

In [249]:
x=df1.iloc[:,:-1]
y=df1.iloc[:,-1:]


col1      col2         2      col3      col4
885 -0.188552 -1.067297 -0.352234 -1.329755  0.878482

In [255]:
x=x.rename(columns={
    2:"col5"
})

In [272]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12)

In [257]:
Model1.fit(x_train,y_train)

DecisionTreeClassifier()

In [260]:
df1.head(1)

col1      col2         2      col3      col4  target
414 -0.677574  0.521671  0.158935 -2.100795 -1.464907       1

In [264]:
Model1.predict([[-0.677574,	0.521671,	0.158935,	-2.100795,	-1.464907]])

C:\Users\Waris Hayyat\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [265]:
x=df2.iloc[:,:-1]
y=df2.iloc[:,-1:]

In [266]:
x=x.rename(columns={
    2:"col5"
})

In [267]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12)

In [268]:
Model2.fit(x_train,y_train)

DecisionTreeClassifier()

In [269]:
Model2.predict([[-0.677574,	0.521671,	0.158935,	-2.100795,	-1.464907]])

C:\Users\Waris Hayyat\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [271]:
x=df3.iloc[:,:-1]
y=df3.iloc[:,-1:]
x=x.rename(columns={
    2:"col5"
})

In [273]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12)

In [274]:
Model3.fit(x_train,y_train)

DecisionTreeClassifier()

In [275]:
Model3.predict([[-0.677574,	0.521671,	0.158935,	-2.100795,	-1.464907]])

C:\Users\Waris Hayyat\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [290]:
from sklearn.datasets import make_classification

In [291]:
x,y=make_classification(n_samples=100,n_features=6,n_informative=3)

In [294]:
df=pd.DataFrame(x)
dt=pd.DataFrame(y)

In [296]:
df=pd.concat((df,dt),axis=1)

In [310]:
def row_sample(df,percent):
    return df.sample(int(percent * df.shape[0]))

In [309]:
row_sample(df,percent=0.4)

TypeError: expected a sequence of integers or a single integer, got '40.0'

In [304]:
df.shape[0]

100