In [161]:
class LinearRegression:
    def __init__ (self):
        #we find slope and intercept for every datapoint.
        self.b = None
        self.m = None

    def fitData(self, x_train, y_train):
        num = 0
        den = 0
        for i in range(x_train.shape[0]):
    
            num += (x_train[i] - x_train.mean()) * (y_train[i] - y_train.mean())
            den += (x_train[i] - x_train.mean()) * (x_train[i] - x_train.mean())

        self.m = num / den
        self.b = y_train.mean() - (self.m * x_train.mean())
        print(self.m)
        print(self.b)
    def prediction(self, x_test):
        return self.m * x_test + self.b

In [146]:
import numpy as np
import pandas as pd

In [147]:
df = pd.read_csv("placement1.csv")
x = df[["cgpa"]].values
y = df[["package"]].values

In [148]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [173]:
reg=LinearRegression()
reg.fitData(x_train,y_train) #these are our slope and itercept.
reg.prediction(x_test[2])

[0.55795197]
[-0.89611192]


array([2.38464568])

In [166]:
y_test

array([[4.1 ],
       [3.49],
       [2.08],
       [2.33],
       [1.94],
       [1.48],
       [1.86],
       [3.09],
       [4.21],
       [2.87],
       [3.65],
       [4.  ],
       [2.89],
       [2.6 ],
       [2.99],
       [3.25],
       [1.86],
       [3.67],
       [2.37],
       [3.42],
       [2.48],
       [3.65],
       [2.6 ],
       [2.83],
       [4.08],
       [2.56],
       [3.58],
       [3.81],
       [4.09],
       [2.01],
       [3.63],
       [2.92],
       [3.51],
       [1.94],
       [2.21],
       [3.34],
       [3.34],
       [3.23],
       [2.01],
       [2.61]])

In [165]:
x_test

array([[8.58],
       [7.15],
       [5.88],
       [6.22],
       [4.57],
       [4.79],
       [5.32],
       [6.86],
       [8.35],
       [6.87],
       [8.94],
       [7.9 ],
       [6.93],
       [5.91],
       [7.32],
       [7.82],
       [5.09],
       [7.42],
       [6.94],
       [7.73],
       [6.19],
       [7.28],
       [6.73],
       [7.2 ],
       [8.21],
       [6.75],
       [7.87],
       [7.6 ],
       [8.63],
       [5.12],
       [8.15],
       [7.36],
       [8.31],
       [6.6 ],
       [6.59],
       [7.47],
       [7.93],
       [6.29],
       [6.37],
       [6.47]])

In [169]:
x_test.shape

(40, 1)

In [170]:
y_test.shape

(40, 1)

In [171]:
x_test[2]

array([5.88])

In [172]:
y_test[2]

array([2.08])