In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

C:\Users\Waris Hayyat\AppData\Local\Temp\ipykernel_1444\1661535507.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df=pd.read_csv("placement1.csv")
df.sample()

cgpa  package
72  7.78     3.62

In [3]:
x=df[["cgpa"]].values
y=df[["package"]].values

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [5]:
lr=LinearRegression()

In [6]:
lr.fit(x_train,y_train)

LinearRegression()

In [7]:
lr.coef_

array([[0.55795197]])

In [8]:
lr.intercept_

array([-0.89611192])

In [12]:
#Now work for own class.

In [9]:
class LinearRegression:
    def __init__(self):
        self.m=None
        self.b=None
    def Fitdata(self,x_train,y_train):
        neu=0
        den=0
        #first calculate the coefficent
        for i in range(x_train.shape[0]):
            neu += (x_train[i] - x_train.mean()) * (y_train[i] - y_train.mean())
            den += (x_train[i] - x_train.mean()) * (x_train[i] - x_train.mean()) 

        self.m = neu/den
        #Now the intercept is:
        self.b = y_train.mean() - (self.m * x_train.mean())
        print("Intercept_:",self.b)
        print("coef_",self.m)
    def predict_Result(self,x_test):
        return (self.m * x_test) + self.b

In [10]:
lr=LinearRegression()
lr.Fitdata(x_train,y_train)
cgpa=int(input("Enter cgpa between 4 to 9:"))
lr.predict_Result([cgpa])

Intercept_: [-0.89611192]
coef_ [0.55795197]


Enter cgpa between 4 to 9: 5


array([1.89364794])