In [1]:
import transformers
from transformers import pipeline

In [4]:
query=pipeline("ner")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


# pipeline
# 1:text clasification
## 2:question answer
# 3:nae entity recognantion
# 4:translation
# 5:text genration and many more

In [8]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier("I am disgusting to learn transformers")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


[{'label': 'NEGATIVE', 'score': 0.9991381168365479}]

In [10]:
from transformers import pipeline

classifier = pipeline("ner")
classifier("my name is waris i live in pakistan")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Hardware accelerator e.g. GPU is

[{'entity': 'I-PER',
  'score': 0.94001794,
  'index': 4,
  'word': 'war',
  'start': 11,
  'end': 14},
 {'entity': 'I-PER',
  'score': 0.877061,
  'index': 5,
  'word': '##is',
  'start': 14,
  'end': 16},
 {'entity': 'I-LOC',
  'score': 0.84817624,
  'index': 9,
  'word': 'p',
  'start': 27,
  'end': 28},
 {'entity': 'I-LOC',
  'score': 0.9788031,
  'index': 10,
  'word': '##aki',
  'start': 28,
  'end': 31},
 {'entity': 'I-LOC',
  'score': 0.99240583,
  'index': 11,
  'word': '##stan',
  'start': 31,
  'end': 35}]

In [14]:
from transformers import pipeline

classifier = pipeline("text-generation")
classifier("my name is waris i live in pakistan")

No model was supplied, defaulted to openai-community/gpt2 and revision 6c0e608 (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'my name is waris i live in pakistan. I\'m very sad," her husband wrote in her first private message, a month after she disappeared.\n\n"My life is not my right and I won\'t allow anyone to destroy my'}]

In [17]:
from transformers import pipeline
from transformers import AutoTokenizer

# AutoTokenizer_class

In [22]:
classifier = AutoTokenizer.from_pretrained("bert-base-cased")

text = ["i am waris,"," i was going to school when i was kid"]

token = classifier(text,padding=True,truncation=True,return_tensors='tf')
print(token)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


{'input_ids': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[ 101,  178, 1821, 1594, 1548,  117,  102,    0,    0,    0,    0],
       [ 101,  178, 1108, 1280, 1106, 1278, 1165,  178, 1108, 5102,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


In [24]:
text = "tokenization is all you need"

token = classifier.tokenize(text)
print("token",token)

ids = classifier.convert_tokens_to_ids(token)
print("ids",ids)

token ['token', '##ization', 'is', 'all', 'you', 'need']
ids [22559, 2734, 1110, 1155, 1128, 1444]


In [26]:
token_decode = classifier.decode(ids)
print("decode_token:----->  ",token_decode)

decode_token:----->   tokenization is all you need


# ModelSpecific Tokenizer
# work with specific pretrain models

In [38]:
#like bert
from transformers import BertTokenizer

check_point = "bert-base-uncased"

token = BertTokenizer.from_pretrained(check_point)

#tokenize the sample text

input = token("Attention is all about the consistency",padding=True,truncation=True,return_tensors='tf')

print(input)


{'input_ids': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=
array([[  101,  3086,  2003,  2035,  2055,  1996, 18700,   102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


In [37]:
#like gpt2
from transformers import GPT2Tokenizer

check_point = "gpt2"

token = GPT2Tokenizer.from_pretrained(check_point)

#tokenize the sample text

input = token("Attention is all about the consistency")

print(input)


{'input_ids': [8086, 1463, 318, 477, 546, 262, 15794], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}


In [39]:
#like gpt2
from transformers import RobertaTokenizer

check_point = "gpt2"

token = RobertaTokenizer.from_pretrained(check_point)

#tokenize the sample text

input = token("Attention is all about the consistency")

print(input)


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'RobertaTokenizer'.


{'input_ids': [50257, 8086, 1463, 318, 477, 546, 262, 15794, 50258], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}


/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


# Auto Model class

In [52]:
from transformers import AutoModel

model_checkpoint = "bert-base-uncased"

tokenizer=AutoTokenizer.from_pretrained(model_checkpoint)
text = "Attention is all you need"
inputs=token(text,return_tensors='tf')

model = AutoModel.from_pretrained(model_checkpoint)
output=model(**inputs)
print(output)

# AutoModel for sequence classification
# AutoModel for CasualLm
# AutoModek for token classification

In [67]:
#AutoModelForSequenceClassification
from transformers import AutoModelForSequenceClassification,AutoModelForCausalLM,AutoModelForTokenClassification
import tensorflow as tf
import numpy
model_checkpoint = "bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint)

text = tokenizer("Hello this is an exampke for sequnec classification",return_tensors='pt')

output =model(**text)

logits = output.logits.detach().numpy()
result = numpy.argmax(logits)
print(result)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


1


In [81]:
#AutoModelForCasualLM

from transformers import AutoModelForCausalLM
import numpy

model_checkpoint="gpt2"

token = AutoTokenizer.from_pretrained(model_checkpoint)

input = token("Once there was a crow.he was very thristy",return_tensors='pt')

model = AutoModelForCausalLM.from_pretrained(model_checkpoint)

result=model.generate(input['input_ids'],max_length=100,num_return_sequences=1)

#decode the result and genrate the text

genrated_text = token.decode(result[0])

print(genrated_text)



The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Once there was a crow.he was very thristy and very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong.he was very strong


# AutoConfigure class

In [84]:
from transformers import AutoConfig

config = AutoConfig.from_pretrained("bert-base-cased")

print(config)

config.hidden_act = "relu"

print(config)

BertConfig {
  "_name_or_path": "bert-base-cased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}

BertConfig {
  "_name_or_path": "bert-base-cased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "relu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps

# Datasets class

In [101]:
!pip uninstall pyarrow -y
!pip install pyarrow


Found existing installation: pyarrow 17.0.0
Uninstalling pyarrow-17.0.0:
  Successfully uninstalled pyarrow-17.0.0
  Using cached pyarrow-17.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Using cached pyarrow-17.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (39.9 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 17.0.0 which is incompatible.
ibis-framework 8.0.0 requires pyarrow<16,>=2, but you have pyarrow 17.0.0 which is incompatible.


In [1]:
!pip install --upgrade pyarrow


In [2]:
from datasets import load_dataset

dataset = load_dataset("imdb")
dataset

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [3]:
train_subset = dataset["train"].select(range(10000))
train_subset

Dataset({
    features: ['text', 'label'],
    num_rows: 10000
})

In [5]:
dataset["train"].features

{'text': Value(dtype='string', id=None),
 'label': ClassLabel(names=['neg', 'pos'], id=None)}

In [7]:
dataset["train"][0]

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

# train_test datasets

In [9]:
split_dataset = dataset["train"].train_test_split(test_size=0.1)

train_dataset = split_dataset["train"]
test_dataset = split_dataset["test"]

test_dataset

Dataset({
    features: ['text', 'label'],
    num_rows: 2500
})

# training_arguments

In [11]:
from transformers import TrainingArguments
t_arg = TrainingArguments('test-trainer')

t_arg

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=no,
eval_use_gather_object=False,
evaluation_strategy=None,
fp16=

# trainer_api
# .train
# .evaluate
# .save
# .predict
# .log

In [ ]:
# full model training
from transformers import Trainer,AutoTokenizer,AutoModelForSequenceClassification,TrainingArguments
from datasets import load_dataset
import numpy as np
from sklearn.metrics import accuracy_score


#load_the datasets
dataset = load_dataset("imdb")

#load tokenizer and model
token = AutoTokenizer.from_pretrained("bert-base-cased")
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased")

#tokenize the text
def tokenization_text(example):
    return token(example["text"],padding=True,truncation=True)

tokenize_dataset = dataset.map(tokenization_text,batched=True)

#define the training_Arguments

argument = TrainingArguments(
    "test-trainer",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=5,
    weight_decay=0.01,
    push_to_hub=False,
)

#define the compute metrics
def compute_metrics(p):
  preds = np.argmax(p.predictions,axis=1)
  return {"accuracy":accuracy_score(p.label_ids,preds)}

#intialize the trainer
trainer = Trainer(
    model,
    argument,
    train_dataset=tokenize_dataset["train"],
    eval_dataset=tokenize_dataset["test"],
    compute_metrics=compute_metrics,
)

#train the model
trainer.train()


#evaluate the model
result = trainer.evaluate()

print(result)

#save the model
trainer.save_model()